[2024-04-13T12:53:48.771+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-13T12:53:48.812+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Process_W3_Data.DateTable manual__2024-04-13T12:53:29.193444+00:00 [queued]>
[2024-04-13T12:53:48.828+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Process_W3_Data.DateTable manual__2024-04-13T12:53:29.193444+00:00 [queued]>
[2024-04-13T12:53:48.828+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-13T12:53:48.854+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): DateTable> on 2024-04-13 12:53:29.193444+00:00
[2024-04-13T12:53:48.864+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=56347) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-13T12:53:48.867+0000] {standard_task_runner.py:63} INFO - Started process 56351 to run task
[2024-04-13T12:53:48.868+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Process_W3_Data', 'DateTable', 'manual__2024-04-13T12:53:29.193444+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/w3c.py', '--cfg-path', '/tmp/tmpkbvdo1_x']
[2024-04-13T12:53:48.872+0000] {standard_task_runner.py:91} INFO - Job 263: Subtask DateTable
[2024-04-13T12:53:48.960+0000] {task_command.py:426} INFO - Running <TaskInstance: Process_W3_Data.DateTable manual__2024-04-13T12:53:29.193444+00:00 [running]> on host 426f0b9f9d71
[2024-04-13T12:53:49.188+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Process_W3_Data' AIRFLOW_CTX_TASK_ID='DateTable' AIRFLOW_CTX_EXECUTION_DATE='2024-04-13T12:53:29.193444+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-13T12:53:29.193444+00:00'
[2024-04-13T12:53:49.191+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-13T12:53:49.508+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-13T12:53:49.509+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-13T12:53:49.533+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Process_W3_Data, task_id=DateTable, execution_date=20240413T125329, start_date=20240413T125348, end_date=20240413T125349
[2024-04-13T12:53:49.608+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-13T12:53:49.679+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-13T12:53:49.687+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
