[2024-04-12T16:13:13.171+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-12T16:13:13.213+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Process_W3_Data.validate_and_clean_data manual__2024-04-12T16:12:31.911827+00:00 [queued]>
[2024-04-12T16:13:13.230+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Process_W3_Data.validate_and_clean_data manual__2024-04-12T16:12:31.911827+00:00 [queued]>
[2024-04-12T16:13:13.230+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-12T16:13:13.310+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): validate_and_clean_data> on 2024-04-12 16:12:31.911827+00:00
[2024-04-12T16:13:13.325+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=40641) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-12T16:13:13.328+0000] {standard_task_runner.py:63} INFO - Started process 40643 to run task
[2024-04-12T16:13:13.337+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Process_W3_Data', 'validate_and_clean_data', 'manual__2024-04-12T16:12:31.911827+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/w3c.py', '--cfg-path', '/tmp/tmpgm970tb7']
[2024-04-12T16:13:13.346+0000] {standard_task_runner.py:91} INFO - Job 247: Subtask validate_and_clean_data
[2024-04-12T16:13:13.477+0000] {task_command.py:426} INFO - Running <TaskInstance: Process_W3_Data.validate_and_clean_data manual__2024-04-12T16:12:31.911827+00:00 [running]> on host 426f0b9f9d71
[2024-04-12T16:13:13.662+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Process_W3_Data' AIRFLOW_CTX_TASK_ID='validate_and_clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T16:12:31.911827+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-12T16:12:31.911827+00:00'
[2024-04-12T16:13:13.666+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-12T16:13:17.382+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-12T16:13:17.383+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-12T16:13:17.411+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Process_W3_Data, task_id=validate_and_clean_data, execution_date=20240412T161231, start_date=20240412T161313, end_date=20240412T161317
[2024-04-12T16:13:17.466+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-12T16:13:17.527+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-12T16:13:17.529+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
