[2024-04-12T16:12:48.052+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-12T16:12:48.123+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Process_W3_Data.DateTable manual__2024-04-12T16:12:31.911827+00:00 [queued]>
[2024-04-12T16:12:48.153+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Process_W3_Data.DateTable manual__2024-04-12T16:12:31.911827+00:00 [queued]>
[2024-04-12T16:12:48.154+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-12T16:12:48.211+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): DateTable> on 2024-04-12 16:12:31.911827+00:00
[2024-04-12T16:12:48.244+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=40609) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-12T16:12:48.248+0000] {standard_task_runner.py:63} INFO - Started process 40613 to run task
[2024-04-12T16:12:48.258+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Process_W3_Data', 'DateTable', 'manual__2024-04-12T16:12:31.911827+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/w3c.py', '--cfg-path', '/tmp/tmphkhdrjvn']
[2024-04-12T16:12:48.294+0000] {standard_task_runner.py:91} INFO - Job 241: Subtask DateTable
[2024-04-12T16:12:48.497+0000] {task_command.py:426} INFO - Running <TaskInstance: Process_W3_Data.DateTable manual__2024-04-12T16:12:31.911827+00:00 [running]> on host 426f0b9f9d71
[2024-04-12T16:12:48.863+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Process_W3_Data' AIRFLOW_CTX_TASK_ID='DateTable' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T16:12:31.911827+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-12T16:12:31.911827+00:00'
[2024-04-12T16:12:48.867+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-12T16:12:49.367+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-12T16:12:49.368+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-12T16:12:49.386+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Process_W3_Data, task_id=DateTable, execution_date=20240412T161231, start_date=20240412T161248, end_date=20240412T161249
[2024-04-12T16:12:49.437+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-12T16:12:49.517+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-12T16:12:49.521+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
